language: rust
rust: nightly
script:
    - "sudo apt-get update && sudo apt-get install python-virtualenv"
    - "cargo build --release --verbose"
    - "cargo test --release --verbose"
    - "virtualenv .venv"
    - ". .venv/bin/activate"
    - "pip install -r tests/test-requirements.txt"
    - "python tests/testapp.py &"
    - "nosetests -sv tests/"
notifications:
  email: false
